### ISSUE TITLE
cs in region

### ISSUE THREAD

**Issue by unhammer** [emacs-evil/evil-surround#104]
Say I have a bunch of lines
```
#include "a.hpp"
#include "bc.hpp"
#include "def.hpp"
```
where I want to `cs">` every line. I was hoping I could do something like 

- `vapSc"<` (or some more logical key/sequence than `Sc`), or
- `csap"<` 

but I can't find anything like that – is there such a thing, for performing multiple surround-changes at once?

**Comment by ninrod** [comment]
yes. macros. Sample approach, top of my head: 

```
ggqaf"cs"<0qjVj:norm @a`
```

**Comment by unhammer** [comment]
I knew about macros, but didn't know the visual `'<,'>:norm @a` trick, thanks! (Btw, for changing `"`, one doesn't need `f"`, so `qacs">qjV}:norm @a` is enough.) 

So there's nothing "motion-like" – I'd prefer that, but can understand if it's outside of the scope of the package.

**Comment by ninrod** [comment]
yeah I was nervous about `f"` because I use [targets.el](https://github.com/noctuid/targets.el) so everything seeks forward for me and that's not standard. for example, `cib` will change inside parentheses no matter where point is in the line. 

But yes, that would be outside of the package scope in that the package is designed to change/add/remove one surrounding at a time and it is essentially a port of [vim-surround](https://github.com/tpope/vim-surround)

macros and multiple-cursors would be the way to go to do many things in one shot.

**Comment by ninrod** [comment]
hey @unhammer, given the context, can we close this?

**Comment by unhammer** [comment]
oh, right
